# Generated by Django 4.2.30 on 2026-06-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_address_member_join_date_member_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='member',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='member',
            name='height',
        ),
        migrations.RemoveField(
            model_name='member',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='weight',
        ),
    ]
