# Generated by Django 4.2.30 on 2026-08-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_member_address_remove_member_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('calories_target', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='DietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('mid_morning', 'Mid-Morning'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'Dinner')], max_length=30)),
                ('food', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='accounts.dietplan')),
            ],
        ),
    ]
