import { useCallback, useEffect, useState } from "react";
import { FiEdit2, FiEye, FiPlus, FiRefreshCw, FiSave, FiTrash2, FiX } from "react-icons/fi";
import api from "../services/api";
import Loading from "../components/Loading";
import Table from "../components/Table";
import { getRows } from "../utils/response";

const blankRecord = { member: "", check_in: "", check_out: "", status: "present" };
const messageFrom = (error, fallback) => error.response?.data?.detail || Object.values(error.response?.data || {}).flat().join(" ") || fallback;

export default function Attendance() {
	const [records, setRecords] = useState([]); const [members, setMembers] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [form, setForm] = useState(blankRecord); const [editingId, setEditingId] = useState(null); const [selected, setSelected] = useState(null); const [formOpen, setFormOpen] = useState(false);
	const load = useCallback(async () => { setLoading(true); setError(""); try { const [attendanceResponse, memberResponse] = await Promise.all([api.get("attendance/"), api.get("members/")]); setRecords(getRows(attendanceResponse.data)); setMembers(getRows(memberResponse.data)); } catch (requestError) { setError(messageFrom(requestError, "Unable to load attendance records.")); } finally { setLoading(false); } }, []);
	useEffect(() => { // The request owns the loading lifecycle for this screen.
		// eslint-disable-next-line react-hooks/set-state-in-effect
		load();
	}, [load]);
	const change = (event) => { const { name, value } = event.target; setForm((current) => ({ ...current, [name]: value })); };
	const memberName = (id) => members.find((member) => member.id === id)?.user || `Member #${id}`;
	const openCreate = () => { setEditingId(null); setForm(blankRecord); setError(""); setSuccess(""); setFormOpen(true); };
	const openEdit = (record) => { setEditingId(record.id); setForm({ member: record.member, check_in: record.check_in || "", check_out: record.check_out || "", status: record.status }); setError(""); setSuccess(""); setFormOpen(true); };
	const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const payload = { member: Number(form.member), check_in: form.check_in, check_out: form.check_out || null, status: form.status }; if (editingId) { await api.patch(`attendance/${editingId}/`, payload); setSuccess("Attendance updated successfully."); } else { await api.post("attendance/", payload); setSuccess("Attendance marked successfully."); } setFormOpen(false); await load(); } catch (requestError) { setError(messageFrom(requestError, "Unable to save attendance.")); } finally { setSaving(false); } };
	const remove = async (record) => { if (!window.confirm(`Delete attendance record ${record.id}?`)) return; setError(""); setSuccess(""); try { await api.delete(`attendance/${record.id}/`); setSuccess("Attendance record deleted successfully."); await load(); } catch (requestError) { setError(messageFrom(requestError, "Unable to delete attendance.")); } };
	const columns = [{ key: "id", label: "ID" }, { key: "member", label: "Member", render: (row) => memberName(row.member) }, { key: "date", label: "Date" }, { key: "check_in", label: "Check in" }, { key: "check_out", label: "Check out", render: (row) => row.check_out || "Still checked in" }, { key: "status", label: "Status" }, { key: "actions", label: "Actions", render: (row) => <div className="flex gap-1"><button onClick={() => setSelected(row)} title="View attendance" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><FiEye size={16} /></button><button onClick={() => openEdit(row)} title="Edit attendance" className="rounded-lg p-2 text-slate-400 hover:bg-teal-50 hover:text-teal-700"><FiEdit2 size={16} /></button><button onClick={() => remove(row)} title="Delete attendance" className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><FiTrash2 size={16} /></button></div> }];
	return <section className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-600">Daily operations</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight text-slate-900">Attendance</h1><p className="mt-2 text-sm text-slate-500">Mark check-ins, record check-outs, and monitor member attendance.</p></div><div className="flex gap-2"><button onClick={openCreate} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-teal-700"><FiPlus size={16} /> Mark attendance</button><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 hover:border-teal-300"><FiRefreshCw size={16} /> Refresh</button></div></div>{error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{success && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</div>}<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="px-5"><Loading label="Loading attendance" /></div> : <Table rows={records} columns={columns} empty="No attendance records found" />}</div>{formOpen && <AttendanceForm form={form} members={members} editingId={editingId} saving={saving} onChange={change} onSubmit={save} onClose={() => setFormOpen(false)} />}{selected && <Details record={selected} memberName={memberName} onClose={() => setSelected(null)} />}</section>;
}

function AttendanceForm({ form, members, editingId, saving, onChange, onSubmit, onClose }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5"><form onSubmit={onSubmit} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Daily operations</p><h2 className="mt-1 font-display text-2xl font-bold text-slate-900">{editingId ? "Edit attendance" : "Mark attendance"}</h2></div><button type="button" onClick={onClose} title="Close" className="p-2 text-slate-400"><FiX /></button></div><label className="mt-6 block text-sm font-bold text-slate-700">Member<select name="member" value={form.member} onChange={onChange} required className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500"><option value="">Select member</option>{members.map((member) => <option key={member.id} value={member.id}>Member #{member.id} {member.user ? `· ${member.user}` : ""}</option>)}</select></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Check in<input name="check_in" type="time" value={form.check_in} onChange={onChange} required className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500" /></label><label className="text-sm font-bold text-slate-700">Check out<input name="check_out" type="time" value={form.check_out} onChange={onChange} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500" /></label></div><label className="mt-4 block text-sm font-bold text-slate-700">Status<select name="status" value={form.status} onChange={onChange} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500"><option value="present">Present</option><option value="absent">Absent</option></select></label><p className="mt-4 text-xs text-slate-500">The API assigns today&apos;s date and prevents duplicate attendance for the same member on the same day.</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60"><FiSave />{saving ? "Saving..." : "Save attendance"}</button></div></form></div>; }
function Details({ record, memberName, onClose }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Attendance details</p><h2 className="mt-1 font-display text-2xl font-bold text-slate-900">Record #{record.id}</h2></div><button onClick={onClose} title="Close" className="p-2 text-slate-400"><FiX /></button></div><dl className="mt-5 divide-y divide-slate-100 text-sm"><Detail label="Member" value={memberName(record.member)} /><Detail label="Date" value={record.date} /><Detail label="Check in" value={record.check_in} /><Detail label="Check out" value={record.check_out || "Still checked in"} /><Detail label="Status" value={record.status} /></dl></div></div>; }
function Detail({ label, value }) { return <div className="flex justify-between gap-4 py-3"><dt className="text-slate-400">{label}</dt><dd className="text-right font-semibold capitalize text-slate-700">{value || "-"}</dd></div>; }
