import { useEffect, useState } from "react";
import { FiActivity, FiArrowUpRight, FiCalendar, FiCreditCard, FiUsers } from "react-icons/fi";
import api from "../services/api";
import Loading from "../components/Loading";
import { getRows } from "../utils/response";

const cards = [["Members", "members", FiUsers, "bg-teal-50 text-teal-700"], ["Trainers", "trainers", FiActivity, "bg-amber-50 text-amber-700"], ["Active plans", "plans", FiArrowUpRight, "bg-sky-50 text-sky-700"], ["Attendance records", "attendance", FiCalendar, "bg-rose-50 text-rose-700"]];
export default function Dashboard() {
  const [counts, setCounts] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { Promise.all(cards.map(([, endpoint]) => api.get(`${endpoint}/`))).then((responses) => setCounts(Object.fromEntries(responses.map((response, index) => [cards[index][1], getRows(response.data).length])))).catch(() => setError("Some dashboard metrics could not be loaded from the API.")).finally(() => setLoading(false)); }, []);
  return <section className="space-y-8"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-600">Overview</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight text-slate-900">Good morning, {localStorage.getItem("username") || "there"}.</h1><p className="mt-2 text-sm text-slate-500">Here is the current pulse of your gym operations.</p></div>{error && <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">{error}</div>}{loading ? <Loading /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, endpoint, Icon, color]) => <div key={endpoint} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className={`grid h-11 w-11 place-items-center rounded-xl ${color}`}><Icon size={20} /></div><span className="text-xs font-bold uppercase tracking-wider text-slate-300">Live</span></div><p className="mt-6 text-sm text-slate-500">{label}</p><p className="mt-1 font-display text-3xl font-bold text-slate-900">{counts[endpoint] ?? 0}</p></div>)}</div>}<div className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-2xl bg-slate-900 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-300">FitSphere intelligence</p><h2 className="mt-3 max-w-lg font-display text-3xl font-bold">Plans that keep members moving.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Use the Workout Plans and Diet Plans modules to generate personalized recommendations from live member profiles.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-7"><div className="flex items-center gap-3"><FiCreditCard className="text-teal-600" /><h2 className="font-bold text-slate-900">Quick links</h2></div><div className="mt-5 grid gap-2 text-sm font-semibold text-slate-600"><a href="/members" className="rounded-lg bg-slate-50 px-3 py-2 hover:text-teal-700">Review member profiles</a><a href="/attendance" className="rounded-lg bg-slate-50 px-3 py-2 hover:text-teal-700">Check attendance</a></div></div></div></section>;
}
