import { useCallback, useEffect, useMemo, useState } from "react";
import { FiEdit2, FiPlus, FiRefreshCw, FiSave, FiTrash2, FiX } from "react-icons/fi";
import api from "../services/api";
import Loading from "../components/Loading";
import Table from "../components/Table";
import { getRows } from "../utils/response";

const blankEnrollment = { member: "", plan: "", start_date: "", status: "active" };
const messageFrom = (error, fallback) => error.response?.data?.detail || Object.values(error.response?.data || {}).flat().join(" ") || fallback;

export default function Enrollments() {
	const [enrollments, setEnrollments] = useState([]); const [members, setMembers] = useState([]); const [plans, setPlans] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [form, setForm] = useState(blankEnrollment); const [editingId, setEditingId] = useState(null); const [formOpen, setFormOpen] = useState(false);
	const load = useCallback(async () => { setLoading(true); setError(""); try { const [enrollmentResponse, memberResponse, planResponse] = await Promise.all([api.get("enrollments/"), api.get("members/"), api.get("plans/")]); setEnrollments(getRows(enrollmentResponse.data)); setMembers(getRows(memberResponse.data)); setPlans(getRows(planResponse.data)); } catch (requestError) { setError(messageFrom(requestError, "Unable to load enrollment data.")); } finally { setLoading(false); } }, []);
	useEffect(() => { // The request owns the loading lifecycle for this screen.
		// eslint-disable-next-line react-hooks/set-state-in-effect
		load();
	}, [load]);
	const selectedPlan = useMemo(() => plans.find((plan) => String(plan.id) === String(form.plan)), [plans, form.plan]);
	const estimatedEndDate = useMemo(() => { if (!form.start_date || !selectedPlan) return ""; const date = new Date(`${form.start_date}T00:00:00`); date.setMonth(date.getMonth() + Number(selectedPlan.duration_months)); return date.toISOString().slice(0, 10); }, [form.start_date, selectedPlan]);
	const change = (event) => { const { name, value } = event.target; setForm((current) => ({ ...current, [name]: value })); };
	const openCreate = () => { setEditingId(null); setForm(blankEnrollment); setError(""); setSuccess(""); setFormOpen(true); };
	const openEdit = (enrollment) => { setEditingId(enrollment.id); setForm({ member: enrollment.member, plan: enrollment.plan, start_date: enrollment.start_date, status: enrollment.status }); setError(""); setSuccess(""); setFormOpen(true); };
	const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const payload = { member: Number(form.member), plan: Number(form.plan), start_date: form.start_date, status: form.status }; if (editingId) { await api.patch(`enrollments/${editingId}/`, payload); setSuccess("Enrollment updated successfully."); } else { await api.post("enrollments/", payload); setSuccess("Enrollment created successfully."); } setFormOpen(false); await load(); } catch (requestError) { setError(messageFrom(requestError, "Unable to save enrollment.")); } finally { setSaving(false); } };
	const remove = async (enrollment) => { if (!window.confirm(`Delete enrollment ${enrollment.id}?`)) return; setError(""); setSuccess(""); try { await api.delete(`enrollments/${enrollment.id}/`); setSuccess("Enrollment deleted successfully."); await load(); } catch (requestError) { setError(messageFrom(requestError, "Unable to delete enrollment.")); } };
	const memberName = (id) => members.find((member) => member.id === id)?.user || `Member #${id}`;
	const planName = (id) => plans.find((plan) => plan.id === id)?.name || `Plan #${id}`;
	const columns = [{ key: "id", label: "ID" }, { key: "member", label: "Member", render: (row) => memberName(row.member) }, { key: "plan", label: "Plan", render: (row) => planName(row.plan) }, { key: "start_date", label: "Starts" }, { key: "end_date", label: "Ends" }, { key: "status", label: "Status" }, { key: "actions", label: "Actions", render: (row) => <div className="flex gap-1"><button onClick={() => openEdit(row)} title="Edit enrollment" className="rounded-lg p-2 text-slate-400 hover:bg-teal-50 hover:text-teal-700"><FiEdit2 size={16} /></button><button onClick={() => remove(row)} title="Delete enrollment" className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><FiTrash2 size={16} /></button></div> }];
	return <section className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-600">Membership</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight text-slate-900">Enrollments</h1><p className="mt-2 text-sm text-slate-500">Assign members to plans and track their calculated expiry dates.</p></div><div className="flex gap-2"><button onClick={openCreate} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-teal-700"><FiPlus size={16} /> Add enrollment</button><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 hover:border-teal-300"><FiRefreshCw size={16} /> Refresh</button></div></div>{error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{success && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</div>}<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="px-5"><Loading label="Loading enrollments" /></div> : <Table rows={enrollments} columns={columns} empty="No enrollments found" />}</div>{formOpen && <EnrollmentForm form={form} members={members} plans={plans} estimatedEndDate={estimatedEndDate} editingId={editingId} saving={saving} onChange={change} onSubmit={save} onClose={() => setFormOpen(false)} />}</section>;
}

function EnrollmentForm({ form, members, plans, estimatedEndDate, editingId, saving, onChange, onSubmit, onClose }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5"><form onSubmit={onSubmit} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Membership</p><h2 className="mt-1 font-display text-2xl font-bold text-slate-900">{editingId ? "Edit enrollment" : "Add enrollment"}</h2></div><button type="button" onClick={onClose} title="Close" className="p-2 text-slate-400"><FiX /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Member<select name="member" value={form.member} onChange={onChange} required className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500"><option value="">Select member</option>{members.map((member) => <option key={member.id} value={member.id}>Member #{member.id} {member.user ? `· ${member.user}` : ""}</option>)}</select></label><label className="text-sm font-bold text-slate-700">Plan<select name="plan" value={form.plan} onChange={onChange} required className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500"><option value="">Select plan</option>{plans.filter((plan) => plan.active).map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.duration_months} months</option>)}</select></label><label className="text-sm font-bold text-slate-700">Start date<input name="start_date" type="date" value={form.start_date} onChange={onChange} required className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500" /></label><label className="text-sm font-bold text-slate-700">Status<select name="status" value={form.status} onChange={onChange} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500"><option value="active">Active</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select></label></div>{estimatedEndDate && <p className="mt-4 rounded-xl bg-teal-50 px-4 py-3 text-sm text-teal-800">Estimated end date: <strong>{estimatedEndDate}</strong>. The API calculates and stores the authoritative date.</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60"><FiSave />{saving ? "Saving..." : "Save enrollment"}</button></div></form></div>; }
