import { useCallback, useEffect, useMemo, useState } from "react";
import { FiEye, FiPlus, FiRefreshCw, FiSave, FiX } from "react-icons/fi";
import api from "../services/api";
import Loading from "../components/Loading";
import Table from "../components/Table";
import { getRows } from "../utils/response";

const blankPayment = { enrollment: "", payment_method: "upi", status: "paid" };
const messageFrom = (error, fallback) => error.response?.data?.detail || Object.values(error.response?.data || {}).flat().join(" ") || fallback;

export default function Payments() {
	const [payments, setPayments] = useState([]); const [enrollments, setEnrollments] = useState([]); const [plans, setPlans] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [form, setForm] = useState(blankPayment); const [selected, setSelected] = useState(null); const [formOpen, setFormOpen] = useState(false);
	const load = useCallback(async () => { setLoading(true); setError(""); try { const [paymentResponse, enrollmentResponse, planResponse] = await Promise.all([api.get("payments/"), api.get("enrollments/"), api.get("plans/")]); setPayments(getRows(paymentResponse.data)); setEnrollments(getRows(enrollmentResponse.data)); setPlans(getRows(planResponse.data)); } catch (requestError) { setError(messageFrom(requestError, "Unable to load payment data.")); } finally { setLoading(false); } }, []);
	useEffect(() => { // The request owns the loading lifecycle for this screen.
		// eslint-disable-next-line react-hooks/set-state-in-effect
		load();
	}, [load]);
	const selectedEnrollment = useMemo(() => enrollments.find((item) => String(item.id) === String(form.enrollment)), [enrollments, form.enrollment]);
	const selectedPlan = useMemo(() => plans.find((plan) => plan.id === selectedEnrollment?.plan), [plans, selectedEnrollment]);
	const change = (event) => { const { name, value } = event.target; setForm((current) => ({ ...current, [name]: value })); };
	const enrollmentLabel = (id) => { const enrollment = enrollments.find((item) => item.id === id); return enrollment ? `#${id} · ${selectedPlanName(enrollment.plan)}` : `Enrollment #${id}`; };
	const selectedPlanName = (id) => plans.find((plan) => plan.id === id)?.name || `Plan #${id}`;
	const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { await api.post("payments/", { enrollment: Number(form.enrollment), payment_method: form.payment_method, status: form.status }); setForm(blankPayment); setFormOpen(false); setSuccess("Payment recorded successfully. Amount was calculated by the server."); await load(); } catch (requestError) { setError(messageFrom(requestError, "Unable to record payment.")); } finally { setSaving(false); } };
	const columns = [{ key: "id", label: "ID" }, { key: "enrollment", label: "Enrollment", render: (row) => enrollmentLabel(row.enrollment) }, { key: "amount", label: "Amount" }, { key: "payment_method", label: "Method", render: (row) => row.payment_method.toUpperCase() }, { key: "status", label: "Status" }, { key: "payment_date", label: "Date" }, { key: "actions", label: "Actions", render: (row) => <button onClick={() => setSelected(row)} title="View payment" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><FiEye size={16} /></button> }];
	return <section className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-600">Finance</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight text-slate-900">Payments</h1><p className="mt-2 text-sm text-slate-500">Record enrollment payments with amount validation handled by Django.</p></div><div className="flex gap-2"><button onClick={() => { setForm(blankPayment); setError(""); setSuccess(""); setFormOpen(true); }} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-teal-700"><FiPlus size={16} /> Record payment</button><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 hover:border-teal-300"><FiRefreshCw size={16} /> Refresh</button></div></div>{error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{success && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</div>}<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="px-5"><Loading label="Loading payments" /></div> : <Table rows={payments} columns={columns} empty="No payments found" />}</div>{formOpen && <PaymentForm form={form} enrollments={enrollments} selectedPlan={selectedPlan} saving={saving} onChange={change} onSubmit={save} onClose={() => setFormOpen(false)} planName={selectedPlanName} />}{selected && <PaymentDetails payment={selected} enrollmentLabel={enrollmentLabel} onClose={() => setSelected(null)} />}</section>;
}

function PaymentForm({ form, enrollments, selectedPlan, saving, onChange, onSubmit, onClose, planName }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5"><form onSubmit={onSubmit} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Finance</p><h2 className="mt-1 font-display text-2xl font-bold text-slate-900">Record payment</h2></div><button type="button" onClick={onClose} title="Close" className="p-2 text-slate-400"><FiX /></button></div><label className="mt-6 block text-sm font-bold text-slate-700">Enrollment<select name="enrollment" value={form.enrollment} onChange={onChange} required className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500"><option value="">Select enrollment</option>{enrollments.map((enrollment) => <option key={enrollment.id} value={enrollment.id}>Enrollment #{enrollment.id} · {planName(enrollment.plan)}</option>)}</select></label>{selectedPlan && <div className="mt-4 rounded-xl bg-teal-50 px-4 py-3 text-sm text-teal-800">Calculated amount: <strong>{selectedPlan.price}</strong><span className="block text-xs text-teal-600">This value comes from the selected membership plan and cannot be overridden here.</span></div>}<div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Payment method<select name="payment_method" value={form.payment_method} onChange={onChange} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500"><option value="cash">Cash</option><option value="upi">UPI</option><option value="card">Card</option></select></label><label className="text-sm font-bold text-slate-700">Status<select name="status" value={form.status} onChange={onChange} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500"><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option></select></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60"><FiSave />{saving ? "Saving..." : "Save payment"}</button></div></form></div>; }
function PaymentDetails({ payment, enrollmentLabel, onClose }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Payment details</p><h2 className="mt-1 font-display text-2xl font-bold text-slate-900">Payment #{payment.id}</h2></div><button onClick={onClose} title="Close" className="p-2 text-slate-400"><FiX /></button></div><dl className="mt-5 divide-y divide-slate-100 text-sm"><Detail label="Enrollment" value={enrollmentLabel(payment.enrollment)} /><Detail label="Amount" value={payment.amount} /><Detail label="Method" value={payment.payment_method?.toUpperCase()} /><Detail label="Status" value={payment.status} /><Detail label="Date" value={payment.payment_date} /></dl></div></div>; }
function Detail({ label, value }) { return <div className="flex justify-between gap-4 py-3"><dt className="text-slate-400">{label}</dt><dd className="text-right font-semibold capitalize text-slate-700">{value || "-"}</dd></div>; }
