import { useCallback, useEffect, useState } from "react";
import { FiEdit2, FiEye, FiPlus, FiRefreshCw, FiSave, FiTrash2, FiX } from "react-icons/fi";
import api from "../services/api";
import Loading from "../components/Loading";
import Table from "../components/Table";
import { getRows } from "../utils/response";

const blankPlan = { name: "", price: "", duration_months: "", description: "", active: true };
const messageFrom = (error, fallback) => error.response?.data?.detail || Object.values(error.response?.data || {}).flat().join(" ") || fallback;
export default function Plans() {
	const [plans, setPlans] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [form, setForm] = useState(blankPlan); const [editingId, setEditingId] = useState(null); const [selected, setSelected] = useState(null); const [formOpen, setFormOpen] = useState(false);
	const load = useCallback(async () => { setLoading(true); setError(""); try { const { data } = await api.get("plans/"); setPlans(getRows(data)); } catch (requestError) { setError(messageFrom(requestError, "Unable to load membership plans.")); } finally { setLoading(false); } }, []);
	useEffect(() => { // The request owns the loading lifecycle for this screen.
		// eslint-disable-next-line react-hooks/set-state-in-effect
		load();
	}, [load]);
	const change = (event) => { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); };
	const openCreate = () => { setEditingId(null); setForm(blankPlan); setError(""); setSuccess(""); setFormOpen(true); };
	const openEdit = (plan) => { setEditingId(plan.id); setForm({ name: plan.name || "", price: plan.price || "", duration_months: plan.duration_months || "", description: plan.description || "", active: plan.active }); setError(""); setSuccess(""); setFormOpen(true); };
	const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const payload = { ...form, price: form.price, duration_months: Number(form.duration_months) }; if (editingId) { await api.patch(`plans/${editingId}/`, payload); setSuccess("Membership plan updated successfully."); } else { await api.post("plans/", payload); setSuccess("Membership plan created successfully."); } setFormOpen(false); await load(); } catch (requestError) { setError(messageFrom(requestError, "Unable to save membership plan.")); } finally { setSaving(false); } };
	const remove = async (plan) => { if (!window.confirm(`Delete ${plan.name}?`)) return; setError(""); setSuccess(""); try { await api.delete(`plans/${plan.id}/`); setSuccess("Membership plan deleted successfully."); await load(); } catch (requestError) { setError(messageFrom(requestError, "Unable to delete membership plan.")); } };
	const columns = [{ key: "id", label: "ID" }, { key: "name", label: "Plan" }, { key: "price", label: "Price" }, { key: "duration_months", label: "Duration", render: (row) => `${row.duration_months} months` }, { key: "active", label: "Status", render: (row) => row.active ? "Active" : "Inactive" }, { key: "actions", label: "Actions", render: (row) => <div className="flex gap-1"><button onClick={() => setSelected(row)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" title="View plan"><FiEye size={16} /></button><button onClick={() => openEdit(row)} className="rounded-lg p-2 text-slate-400 hover:bg-teal-50 hover:text-teal-700" title="Edit plan"><FiEdit2 size={16} /></button><button onClick={() => remove(row)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" title="Delete plan"><FiTrash2 size={16} /></button></div> }];
	return <section className="space-y-6"><Header onCreate={openCreate} onRefresh={load} /><Feedback error={error} success={success} /><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="px-5"><Loading label="Loading membership plans" /></div> : <Table rows={plans} columns={columns} empty="No membership plans found" />}</div>{formOpen && <PlanForm form={form} editingId={editingId} saving={saving} onChange={change} onSubmit={save} onClose={() => setFormOpen(false)} />}{selected && <PlanDetails plan={selected} onClose={() => setSelected(null)} />}</section>;
}

function Header({ onCreate, onRefresh }) { return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-600">Membership</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight text-slate-900">Membership plans</h1><p className="mt-2 text-sm text-slate-500">Create and maintain the plans offered by the gym.</p></div><div className="flex gap-2"><button onClick={onCreate} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-teal-700"><FiPlus size={16} /> Add plan</button><button onClick={onRefresh} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 hover:border-teal-300"><FiRefreshCw size={16} /> Refresh</button></div></div>; }
function Feedback({ error, success }) { return <>{error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{success && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</div>}</>; }
function PlanForm({ form, editingId, saving, onChange, onSubmit, onClose }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5"><form onSubmit={onSubmit} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Membership</p><h2 className="mt-1 font-display text-2xl font-bold text-slate-900">{editingId ? "Edit plan" : "Add plan"}</h2></div><button type="button" onClick={onClose} title="Close" className="p-2 text-slate-400"><FiX /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Name" name="name" value={form.name} onChange={onChange} required /><Field label="Price" name="price" type="number" min="1" step="0.01" value={form.price} onChange={onChange} required /><Field label="Duration (months)" name="duration_months" type="number" min="1" value={form.duration_months} onChange={onChange} required /><label className="flex items-center gap-3 self-end rounded-xl border border-slate-200 px-3 py-3 text-sm font-semibold"><input type="checkbox" name="active" checked={form.active} onChange={onChange} className="accent-teal-600" /> Active plan</label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Description<textarea name="description" value={form.description} onChange={onChange} rows="3" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60"><FiSave />{saving ? "Saving..." : "Save plan"}</button></div></form></div>; }
function Field({ label, name, onChange, ...props }) { return <label className="block text-sm font-bold text-slate-700">{label}<input name={name} onChange={onChange} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-500" {...props} /></label>; }
function PlanDetails({ plan, onClose }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Plan details</p><h2 className="mt-1 font-display text-2xl font-bold text-slate-900">{plan.name}</h2></div><button onClick={onClose} title="Close" className="p-2 text-slate-400"><FiX /></button></div><dl className="mt-5 divide-y divide-slate-100 text-sm"><Detail label="Price" value={plan.price} /><Detail label="Duration" value={`${plan.duration_months} months`} /><Detail label="Status" value={plan.active ? "Active" : "Inactive"} /><Detail label="Description" value={plan.description} /></dl></div></div>; }
function Detail({ label, value }) { return <div className="flex justify-between gap-4 py-3"><dt className="text-slate-400">{label}</dt><dd className="text-right font-semibold text-slate-700">{value || "-"}</dd></div>; }
