spring.application.name=backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/fitsphere
spring.datasource.username=postgres
spring.datasource.password=sangeerthmurali

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Server
server.port=8080